server:
  port: 8761

eureka:
  client:
    # Set the two options below to false for a single server
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: docs-discovery-service
